version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  t_rex:
    image: sourcepole/t-rex
    ports:
      - "6767:6767"
    links:
      - database
    environment:
      - DATABASE_NAME=basiskaart
      - DATABASE_USER=basiskaart
      - DATABASE_PASSWORD=insecure
    volumes:
      - "$PWD/data/in:/var/data/in:ro"
      - "$PWD/data/out:/var/data/out"
      - "$PWD/config:/var/config:ro"

