version: "3.0"
services:
  database:
    image: amsterdam/postgres11
    volumes:
      - "$PWD/config/database:/database"
    ports:
      - "5402:5432"
    environment:
      POSTGRES_DB: basiskaart
      POSTGRES_USER: basiskaart
      POSTGRES_PASSWORD: insecure

  t_rex:
    image: sourcepole/t-rex
    ports:
      - "6767:6767"
    links:
      - database
    environment:
      - DATABASE_NAME=basiskaart
      - DATABASE_USER=basiskaart
      - DATABASE_PASSWORD=insecure
    volumes:
      - "$PWD/data/in:/var/data/in:ro"
      - "$PWD/data/out:/var/data/out"
      - "$PWD/config:/var/config:ro"
      - "$PWD/cache:/var/cache/mvtcache"
      - "$PWD/static:/static"
    command: serve --config  /var/config/topo_wm.toml

  tileserver_gl:
    image: maptiler/tileserver-gl
    # image: local/tileserver_gl
    ports:
      - "8080:80"
    links:
      - t_rex
    volumes:
      - "$PWD/data:/data"
      - "$PWD/config:/var/config:ro"
      - "$PWD/static:/static:ro"
    command: run.sh --verbose -c /var/config/tileserver_cfg.json

  topo_wm:
    build: .
    user: root
    links:
      - tileserver_gl
      - database
    command: >
      mapproxy-seed -c 1 -s /app/seed.yaml -f /app/mapproxy.yaml --seed=topo_wm_kbk,topo_wm_bgt
    volumes:
      - "$PWD/tiles:/mnt/tiles"


